// generated by Fast Light User Interface Designer (fluid) version 1.0304

#ifndef labgui_h
#define labgui_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Box.H>
#include <FL/Fl_PNG_Image.H>
extern Fl_Box *field;
extern Fl_Box *bb;
#include <FL/Fl_Button.H>
#include <iostream>
#include <FL/Fl_Value_Input.H>
extern Fl_Value_Input *initial_v;
Fl_Double_Window* make_window();
void move(void*);
#endif
